require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PotholesController do

  # This should return the minimal set of attributes required to create a valid
  # Pothole. As you add validations to Pothole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PotholesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all potholes as @potholes" do
      pothole = Pothole.create! valid_attributes
      get :index, {}, valid_session
      assigns(:potholes).should eq([pothole])
    end
  end

  describe "GET show" do
    it "assigns the requested pothole as @pothole" do
      pothole = Pothole.create! valid_attributes
      get :show, {:id => pothole.to_param}, valid_session
      assigns(:pothole).should eq(pothole)
    end
  end

  describe "GET new" do
    it "assigns a new pothole as @pothole" do
      get :new, {}, valid_session
      assigns(:pothole).should be_a_new(Pothole)
    end
  end

  describe "GET edit" do
    it "assigns the requested pothole as @pothole" do
      pothole = Pothole.create! valid_attributes
      get :edit, {:id => pothole.to_param}, valid_session
      assigns(:pothole).should eq(pothole)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pothole" do
        expect {
          post :create, {:pothole => valid_attributes}, valid_session
        }.to change(Pothole, :count).by(1)
      end

      it "assigns a newly created pothole as @pothole" do
        post :create, {:pothole => valid_attributes}, valid_session
        assigns(:pothole).should be_a(Pothole)
        assigns(:pothole).should be_persisted
      end

      it "redirects to the created pothole" do
        post :create, {:pothole => valid_attributes}, valid_session
        response.should redirect_to(Pothole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pothole as @pothole" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pothole.any_instance.stub(:save).and_return(false)
        post :create, {:pothole => {  }}, valid_session
        assigns(:pothole).should be_a_new(Pothole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pothole.any_instance.stub(:save).and_return(false)
        post :create, {:pothole => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pothole" do
        pothole = Pothole.create! valid_attributes
        # Assuming there are no other potholes in the database, this
        # specifies that the Pothole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pothole.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => pothole.to_param, :pothole => { "these" => "params" }}, valid_session
      end

      it "assigns the requested pothole as @pothole" do
        pothole = Pothole.create! valid_attributes
        put :update, {:id => pothole.to_param, :pothole => valid_attributes}, valid_session
        assigns(:pothole).should eq(pothole)
      end

      it "redirects to the pothole" do
        pothole = Pothole.create! valid_attributes
        put :update, {:id => pothole.to_param, :pothole => valid_attributes}, valid_session
        response.should redirect_to(pothole)
      end
    end

    describe "with invalid params" do
      it "assigns the pothole as @pothole" do
        pothole = Pothole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pothole.any_instance.stub(:save).and_return(false)
        put :update, {:id => pothole.to_param, :pothole => {  }}, valid_session
        assigns(:pothole).should eq(pothole)
      end

      it "re-renders the 'edit' template" do
        pothole = Pothole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pothole.any_instance.stub(:save).and_return(false)
        put :update, {:id => pothole.to_param, :pothole => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pothole" do
      pothole = Pothole.create! valid_attributes
      expect {
        delete :destroy, {:id => pothole.to_param}, valid_session
      }.to change(Pothole, :count).by(-1)
    end

    it "redirects to the potholes list" do
      pothole = Pothole.create! valid_attributes
      delete :destroy, {:id => pothole.to_param}, valid_session
      response.should redirect_to(potholes_url)
    end
  end

end
